### ISSUE TITLE
CF template fails to deploy - EB solution stack not found

### ISSUE THREAD

**Issue by carter3d** [aws-quickstart/quickstart-dotnet-serverless-cicd#15]
Error in CF (running in us-east-1)

ElasticBeanstalkEnvironment | CREATE_FAILED | No Solution Stack named '64bit Windows Server 2016 v2.3.0 running IIS 10.0' found. (Service: AWSElasticBeanstalk; Status Code: 400; Error Code: InvalidParameterValue;

Looks like the CF template value should be '64bit Windows Server 2016 v2.3.2 running IIS 10.0' based on https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html.

**Comment by virtlima** [comment]
Just added a Parameter for Solution Stack so that you can provide the latest Platforn version as opposed to having this hard coded in the template. Apologize for that, we will work on trying to monitory this in some way to update the default value. However, we will also update documentation.
